openapi: 3.0.4
info:
  title: Lib404 API
  description: |-
    API for the Lib404 website, allowing users to book study desks and lockers. 
    Endpoints provide functionality to manage reservations, check desk/locker availability, 
    create, cancel, or update reservations. 
    Designed for integration with web to enhance the user experience in the library.

    Some useful links:
    - [The Lib404 repository]
    - [The source API definition for the Lib404 project](https://github.com/Khoaaaa/Lib404-Back-end/blob/main/api-doc.yaml)
  termsOfService: http://libraryreservation.com/terms/
  contact:
    email: support@libraryreservation.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
servers:
  - url: https://libraryreservationapi.onrender.com
    description: Production server
  - url: http://localhost:8080
    description: Local server
tags:
  - name: Rooms
    description: Library study rooms management
  - name: Tables
    description: Library study tables reservation and availability
  - name: Users
    description: Operations about user registration, login, profile management
  - name: Lockers
    description: Library locker reservation and availability
  - name: Feedback
    description: User feedback and support requests
paths:
  /rooms:
    post:
      tags:
        - Rooms
      summary: Add a new room to the library.
      description: Add a new room to the library.
      operationId: createNewRoom
      requestBody:
        description: Add a new room to the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Room not added

    get:
      tags:
        - Rooms
      summary: Get all rooms
      description: Retrieve a list of all rooms in the library
      operationId: getAllRooms
      responses:
        '200':
          description: List of rooms returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'

  /rooms/{id}:
    put:
      tags:
        - Rooms
      summary: Update an existing room by id.
      description: Update an existing room by id.
      operationId: updateRoom
      parameters:
        - name: id
          in: path
          description: ID of room to update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent room in the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '404':
          description: Room not found

    get:
      tags:
        - Rooms
      summary: Get room by id.
      description: Get room details by ID.
      operationId: getRoomByID
      parameters:
        - name: id
          in: path
          description: ID of room to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          description: Invalid room ID

    delete:
      tags:
        - Rooms
      summary: Delete a room from the library.
      description: Delete a room from the library.
      operationId: deleteRoom
      parameters:
        - name: id
          in: path
          description: ID of room to delete
          required: true
          schema:
            type: string
      requestBody:
        description: Delete an existing room from the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Room not deleted

  /tables:
    post:
      tags:
        - Tables
      summary: Create a new table
      description: Create a new table with tableId, type, roomId, and optional reservedTime.
      operationId: createNewTable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tableId:
                  type: integer
                type:
                  type: string
                  enum: [single, group]
                roomId:
                  type: integer
                reservedTime:
                  type: integer
                  nullable: true
              required:
                - tableId
                - type
                - roomId
      responses:
        '201':
          description: Table created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

    get:
      tags:
        - Tables
      summary: Get all tables
      description: Retrieve all tables
      operationId: getAllTables
      responses:
        '200':
          description: List of all tables
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Table'
        '500':
          description: Internal server error

  /tables/import:
    get:
      tags:
        - Tables
      summary: Import multiple tables into database
      description: Import a predefined set of tables
      operationId: importTables
      responses:
        '200':
          description: Tables imported successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Table'
        '500':
          description: Internal server error

  /tables/{id}:
    get:
      tags:
        - Tables
      summary: Get table by tableId
      description: Retrieve a table using its tableId
      operationId: getTableByTableID
      parameters:
        - name: id
          in: path
          description: tableId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Table data returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          description: Table not found
        '500':
          description: Internal server error

    put:
      tags:
        - Tables
      summary: Update table information
      description: Update table username, availability, and reservedTime
      operationId: updateTable
      parameters:
        - name: id
          in: path
          description: tableId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                reservedTime:
                  type: integer
                  nullable: true
      responses:
        '200':
          description: Table updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '400':
          description: Invalid parameters
        '404':
          description: Table not found
        '500':
          description: Internal server error

    delete:
      tags:
        - Tables
      summary: Delete table by tableId
      description: Delete a table from database
      operationId: deleteTable
      parameters:
        - name: id
          in: path
          description: tableId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Table deleted successfully
          content:
            application/json:
              example:
                message: 'Table deleted successfully'
        '404':
          description: Table not found
        '500':
          description: Internal server error

  /tables/{id}/clear:
    put:
      tags:
        - Tables
      summary: Clear table reservation (reset username, availability)
      description: Reset table to available state
      operationId: clearTable
      parameters:
        - name: id
          in: path
          description: tableId
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Table cleared successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
        '404':
          description: Table not found
        '500':
          description: Internal server error

  /lockers:
    post:
      tags:
        - Lockers
      summary: Create a new locker.
      description: Add a new locker to the system.
      operationId: createNewLocker
      requestBody:
        description: Locker information to be created.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Locker'
      responses:
        '200':
          description: Locker added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Locker'
        '500':
          description: Internal server error

    get:
      tags:
        - Lockers
      summary: Get all lockers.
      description: Retrieve a list of all lockers.
      operationId: getAllLockers
      responses:
        '200':
          description: List of lockers returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: '#/components/schemas/Locker'
        '500':
          description: Internal server error

  /lockers/import:
    get:
      tags:
        - Lockers
      summary: Import locker data.
      description: Import predefined lockers (1–136) into the system.
      operationId: importLockers
      responses:
        '200':
          description: Lockers imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Lockers imported successfully'
        '500':
          description: Internal server error

  /lockers/{id}:
    get:
      tags:
        - Lockers
      summary: Get locker by LockerId.
      description: Get locker details by LockerId.
      operationId: getLockerByID
      parameters:
        - name: id
          in: path
          required: true
          description: Locker ID
          schema:
            type: string
      responses:
        '200':
          description: Locker details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Locker'
        '404':
          description: Locker not found
        '500':
          description: Internal server error

    put:
      tags:
        - Lockers
      summary: Assign locker to a user.
      description: Update locker availability and assign username (only if locker is available).
      operationId: updateLocker
      parameters:
        - name: id
          in: path
          required: true
          description: Locker ID
          schema:
            type: string
      requestBody:
        description: Username to assign.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: '23521677'
      responses:
        '200':
          description: Locker updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Locker'
        '400':
          description: Username missing or locker not available
        '404':
          description: Locker not found
        '500':
          description: Internal server error

    delete:
      tags:
        - Lockers
      summary: Delete a locker by LockerId.
      description: Remove a locker from the system.
      operationId: deleteLocker
      parameters:
        - name: id
          in: path
          required: true
          description: Locker ID
          schema:
            type: string
      requestBody:
        description: Locker delete request (not required but kept for consistency)
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Locker'
      responses:
        '200':
          description: Locker deleted successfully
          content:
            application/json:
              example:
                message: 'Locker deleted successfully'
        '404':
          description: Locker not found
        '500':
          description: Internal server error

  /lockers/{id}/clear:
    delete:
      tags:
        - Lockers
      summary: Clear locker reservation.
      description: Clear locker (set available = true), remove username, and verify PIN.
      operationId: clearLocker
      parameters:
        - name: id
          in: path
          required: true
          description: Locker ID
          schema:
            type: string
      requestBody:
        description: Username and PIN required to clear locker.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: '23521677'
                pin:
                  type: string
                  example: '1234'
      responses:
        '200':
          description: Locker cleared successfully
          content:
            application/json:
              example:
                message: 'Locker 5 cleared successfully'
        '400':
          description: Missing PIN or locker already available
        '403':
          description: Username mismatch or incorrect PIN
        '404':
          description: Locker not found
        '500':
          description: Internal server error

  /feedback:
    post:
      tags:
        - Feedback
      summary: Submit user feedback.
      description: Submit feedback or support requests from users.
      operationId: createNewFeedback
      requestBody:
        description: User feedback submission
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
        required: true
      responses:
        '201':
          description: Create new feedback with email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'

    get:
      tags:
        - Feedback
      summary: Get all user feedback
      description: Retrieve a list of all user feedback submissions
      operationId: getAllFeedback
      responses:
        '200':
          description: List of feedback returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'

  /feedback/{email}:
    get:
      tags:
        - Feedback
      summary: Get feedback by user email.
      description: Get feedback submissions by user email.
      operationId: getFeedbackByEmail
      parameters:
        - name: email
          in: path
          description: Email of user to return feedback
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Feedback details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
        '404':
          description: Feedback with email not found

components:
  schemas:
    Room:
      properties:
        roomId:
          type: integer
          example: 101
        type:
          type: string
          example: 'Standard'
        floorId:
          type: string
          example: '1'
      required:
        - roomId
        - type
        - floorId

    Table:
      type: object
      properties:
        _id:
          type: string
        tableId:
          type: integer
        type:
          type: string
          enum: [single, group]
        roomId:
          type: integer
        availability:
          type: boolean
        username:
          type: string
          nullable: true
        expiresAt:
          type: string
          format: date-time
          nullable: true
        reservedTime:
          type: integer
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Locker:
      type: object
      properties:
        lockerId:
          type: integer
          example: 1
        availability:
          type: boolean
          example: true
        username:
          type: string
          nullable: true
          example: '23521677'
      required:
        - lockerId
        - availability

    Feedback:
      properties:
        username:
          type: string
          example: '23521677'
        email:
          type: string
          example: '23521677@gm.uit.edu.vn'
        feedbackType:
          type: string
          example: 'Suggestion'
        rating:
          type: integer
          example: 5
        message:
          type: string
          example: 'Great service!'
      required:
        - username
        - email
        - feedbackType
        - rating
        - message
    User:
      properties:
        username:
          type: string
          example: '23521677'
        email:
          type: string
          example: '23521677@gm.uit.edu.vn'
        password:
          type: string
          example: 'securePassword123'
      required:
        - username
        - email
        - password
