openapi: 3.0.4
info:
  title: Library Reservation API
  description: |-
    API for the library reservation website, allowing users to book study desks and lockers. 
    Endpoints provide functionality to manage reservations, check desk/locker availability, 
    create, cancel, or update reservations. 
    Designed for integration with web to enhance the user experience in the library.

    Some useful links:
    - [The Library Reservation repository]
    - [The source API definition for the Library Reservation]
  termsOfService: http://libraryreservation.com/terms/
  contact:
    email: support@libraryreservation.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: Rooms
    description: Library study rooms management
  - name: Tables
    description: Library study tables reservation and availability
  - name: Users
    description: Operations about user registration, login, profile management
  - name: Lockers
    description: Library locker reservation and availability
  - name: Feedback
    description: User feedback and support requests
paths:
  /rooms/{id}:
    put:
      tags:
        - Rooms
      summary: Update an existing room by id.
      description: Update an existing room by id.
      operationId: updateRoom
      parameters:
        - name: id
          in: path
          description: ID of room to update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent room in the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '404':
          description: Room not found

    delete:
      tags:
        - Rooms
      summary: Delete a room from the library.
      description: Delete a room from the library.
      operationId: deleteRoom
      parameters:
        - name: id
          in: path
          description: ID of room to delete
          required: true
          schema:
            type: string
      requestBody:
        description: Delete an existing room from the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Room not deleted

    get:
      tags:
        - Rooms
      summary: Get room by id.
      description: Get room details by ID.
      operationId: getRoomByID
      parameters:
        - name: id
          in: path
          description: ID of room to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          description: Invalid room ID

  /rooms:
    post:
      tags:
        - Rooms
      summary: Add a new room to the library.
      description: Add a new room to the library.
      operationId: createNewRoom
      requestBody:
        description: Add a new room to the library
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '200':
          description: Room added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Room not added

    get:
      tags:
        - Rooms
      summary: Get all rooms
      description: Retrieve a list of all rooms in the library
      operationId: getAllRooms
      responses:
        '200':
          description: List of rooms returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
    
  
components:
  schemas:
    Room:
      properties:
        roomId:
          type: integer
          example: 101
        type:
          type: string
          example: "Standard"
        floorId:
          type: string
          example: "1"
      required:
        - roomId
        - type
        - floorId
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      xml:
        name: category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      xml:
        name: user
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: pet
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header